# metrics setting[Ranking-based]
metrics: ['Recall', 'NDCG']
valid_metric: NDCG@10
topk: [5, 10]

val_interval:
    # rating: "[85.15,100]"
    rating: "[0,100]"

# neg_sampling
neg_sampling:
    popularity: 10