# metrics setting[value-based]
metrics: ['AUC', 'RMSE']
valid_metric: AUC


# defining Label
LABEL_FIELD: rating
threshold:
    rating: 80.0


# data setting
load_col:
    item: ['Whiskey', 'Meta Critic',  'STDEV',  '#',      'Class',  'Cost',   'Super Cluster', 'Cluster', 'body',   'sweet',  'sherry',   'malt',   'aperitif',   'smoky', 'pungent',   'fruity',   'honey',  'floral',   'spicy',  'medicinal',  'nutty',  'winey']