dataset_name: 'movielens1M'
dataset_path: '/opt/ml/workspace/team_git/Model/Context_Awared/ml-1m/ratings.dat'

model_name: 'dfm'

epoch: 100
learning_rate: 0.001
batch_size: 64
weight_decay: 0.0
device: 'cuda:0'
save_dir: './model_saved'